#pragma once
#include <vector>
#include <iostream>
#include <algorithm>
#include <numeric>
#include <fstream>
#include <string>
#include <map>
#include <set>
#include <sstream>
#include <conio.h>
#include "IntCode.h"
#include "IntCode_simple.h"
#include "HelperFunctions.h"
#include "Planet.h"
#include <iomanip>
#include <unordered_set>
#include <unordered_map>
#include <chrono>
#include <thread>
#include "PlanetSys.h"
#include <utility>
#include <stack>
#include "Maze.h"
#include "Maze_simple.h"
#include <random>
#include "SimpGraph.h"
#include <queue>
#include <cassert>
#include "IntCode_char.h"
//#include "Day18HelperFunctions.h"
//#include "Day19HelperFunctions.h"
//#include "Day20HelperFunctions.h"
#include "Day22HelperFunctions.h"
